plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'xyz.sodera.app.passkey'
version = '0.1.0'

android {
  namespace "xyz.sodera.app.passkey"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.credentials:credentials:1.6.0'
  implementation 'androidx.credentials:credentials-play-services-auth:1.6.0'
}
